2024-04-30 17:43:46,611 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 17:43:46,620 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 17:43:47,422 
INFO 
Call started...sid: CA690153528dd05330b1ec43b17cf67ae0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 17:44:40,883 
INFO 
call was a success, male docs: 5, female docs: 6 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\active_call_methods.py", line 94, in handle_successful_call

2024-04-30 17:44:48,635 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 18:01:16,288 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 18:01:16,289 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 18:01:16,718 
INFO 
Call started...sid: CA897e3f5c4bb9243d8dffabd22f52533a 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 18:02:23,117 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:20:42,408 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:20:42,409 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:20:42,856 
INFO 
Call started...sid: CA0790dd7ae10ee6e01d98528463acce57 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:21:23,741 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:21:23,745 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 30, in <module>

2024-04-30 19:21:32,216 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:21:32,218 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:21:32,670 
INFO 
Call started...sid: CAeac4b15782cc29efae13049dfbcd6f2e 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:22:59,185 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:22:59,189 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 30, in <module>

2024-04-30 19:23:05,714 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:23:05,715 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:23:06,153 
INFO 
Call started...sid: CAd3ef4e61f1ff50f75da9f8bed6560809 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:23:14,078 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:23:14,093 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:23:14,109 
INFO 
intro message timeouts count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:23:33,471 
INFO 
invalid key count on intro message: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 69, in handle_intro_message_response

2024-04-30 19:23:33,489 
INFO 
prompt retrys count on intro message: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 70, in handle_intro_message_response

2024-04-30 19:23:33,614 
INFO 
timeouts_count when asking male doctors number: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 111, in ask_male_doctors_number

2024-04-30 19:23:46,737 
INFO 
invalid_input_count when asking male doctors number: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 148, in handle_number_male_doctors_response

2024-04-30 19:23:46,752 
INFO 
male doctors: 5 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 161, in handle_number_male_doctors_response

2024-04-30 19:23:46,871 
INFO 
timeouts_count when asking for female doctors number: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 197, in ask_female_doctors_number

2024-04-30 19:23:58,850 
INFO 
invalid_input_count when asking female doctors number: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 237, in handle_number_female_doctors_response

2024-04-30 19:23:58,865 
INFO 
female doctors: 7 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 248, in handle_number_female_doctors_response

2024-04-30 19:24:07,250 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:25:24,730 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:25:24,731 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:25:25,143 
INFO 
Call started...sid: CA3b53dd9d92460ea46a2572d381270a76 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:25:39,684 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:25:39,700 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:25:39,716 
INFO 
intro message timeouts count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:26:06,027 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:26:06,031 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 30, in <module>

2024-04-30 19:26:23,411 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:26:23,412 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:26:23,776 
INFO 
Call started...sid: CA731d41cc57d8fc149a34098c24c2d713 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:26:37,993 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:26:38,008 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:26:38,024 
INFO 
intro message timeouts count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:26:59,659 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:26:59,673 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:26:59,688 
INFO 
intro message timeouts count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:27:21,319 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:27:21,334 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:27:21,350 
INFO 
intro message timeouts count: 2 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:27:50,327 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:27:50,332 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 30, in <module>

2024-04-30 19:27:55,070 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:27:55,071 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:27:55,462 
INFO 
Call started...sid: CAae47844128c8fa538655d8ac78a41730 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:28:05,013 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:28:05,029 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:28:05,046 
INFO 
intro message timeouts count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:28:26,355 
INFO 
invalid key count on intro message: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 69, in handle_intro_message_response

2024-04-30 19:28:26,370 
INFO 
prompt retrys count on intro message: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 70, in handle_intro_message_response

2024-04-30 19:28:26,489 
INFO 
timeouts_count when asking male doctors number: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 111, in ask_male_doctors_number

2024-04-30 19:28:38,785 
INFO 
invalid_input_count when asking male doctors number: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 148, in handle_number_male_doctors_response

2024-04-30 19:28:38,802 
INFO 
male doctors: 4 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 161, in handle_number_male_doctors_response

2024-04-30 19:28:38,915 
INFO 
timeouts_count when asking for female doctors number: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 197, in ask_female_doctors_number

2024-04-30 19:28:50,501 
INFO 
invalid_input_count when asking female doctors number: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 237, in handle_number_female_doctors_response

2024-04-30 19:28:50,517 
INFO 
female doctors: 9 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 248, in handle_number_female_doctors_response

2024-04-30 19:28:56,603 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:29:47,970 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:29:47,971 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:29:48,488 
INFO 
Call started...sid: CAe6722509a033bcdb0b3f998a509a0abf 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:30:06,425 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:30:06,440 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:30:06,459 
INFO 
intro message timeouts count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:30:20,358 
INFO 
invalid key count on intro message: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 69, in handle_intro_message_response

2024-04-30 19:30:20,373 
INFO 
prompt retrys count on intro message: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 70, in handle_intro_message_response

2024-04-30 19:30:20,497 
INFO 
timeouts_count when asking male doctors number: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 111, in ask_male_doctors_number

2024-04-30 19:30:28,967 
INFO 
invalid_input_count when asking male doctors number: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 148, in handle_number_male_doctors_response

2024-04-30 19:30:28,981 
INFO 
male doctors: 4 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 161, in handle_number_male_doctors_response

2024-04-30 19:30:29,102 
INFO 
timeouts_count when asking for female doctors number: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 197, in ask_female_doctors_number

2024-04-30 19:30:38,550 
INFO 
invalid_input_count when asking female doctors number: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 237, in handle_number_female_doctors_response

2024-04-30 19:30:38,566 
INFO 
female doctors: 7 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 248, in handle_number_female_doctors_response

2024-04-30 19:30:44,513 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:40:15,201 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:40:15,202 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:40:15,618 
INFO 
Call started...sid: CAa6b1d0d9ea1b2a2dbc6d6a37e499650b 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:40:29,838 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:40:29,865 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:40:29,891 
INFO 
intro message timeouts count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:40:51,553 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:40:51,568 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:40:51,588 
INFO 
intro message timeouts count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:41:13,241 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:41:13,257 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:41:13,272 
INFO 
intro message timeouts count: 2 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:41:42,165 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:41:42,169 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 30, in <module>

2024-04-30 19:41:46,512 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:41:46,513 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:41:46,977 
INFO 
Call started...sid: CA93173b279a0dce2ab7cc055035d2cd28 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:42:00,652 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:42:00,668 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:42:00,684 
INFO 
intro message timeouts count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:42:22,299 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:42:22,315 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:42:22,330 
INFO 
intro message timeouts count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:42:48,048 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:42:48,052 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 30, in <module>

2024-04-30 19:44:11,115 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:44:11,116 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 17, in start_server

2024-04-30 19:44:11,556 
INFO 
Call started...sid: CAc8d7bf6c6811ba4ed9571f2d4a98a4f6 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:44:32,029 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:44:32,035 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 33, in <module>

2024-04-30 19:44:39,044 
INFO 
Received phone number: 2894007562. Received clinic id: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:44:39,045 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 18, in start_server

2024-04-30 19:44:39,432 
INFO 
Call started...sid: CAfd3b00c7195b5e9a5a3454bad6be197a 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 74, in call_all_clinics

2024-04-30 19:44:46,230 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:44:46,245 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:44:46,260 
INFO 
intro message timeouts count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:44:57,064 
INFO 
invalid key count on intro message: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 69, in handle_intro_message_response

2024-04-30 19:44:57,079 
INFO 
prompt retrys count on intro message: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 70, in handle_intro_message_response

2024-04-30 19:44:57,196 
INFO 
timeouts_count when asking male doctors number: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 111, in ask_male_doctors_number

2024-04-30 19:45:10,405 
INFO 
invalid_input_count when asking male doctors number: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 148, in handle_number_male_doctors_response

2024-04-30 19:45:10,422 
INFO 
male doctors: 5 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 161, in handle_number_male_doctors_response

2024-04-30 19:45:10,552 
INFO 
timeouts_count when asking for female doctors number: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 197, in ask_female_doctors_number

2024-04-30 19:45:23,806 
INFO 
invalid_input_count when asking female doctors number: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 237, in handle_number_female_doctors_response

2024-04-30 19:45:23,821 
INFO 
female doctors: 7 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 248, in handle_number_female_doctors_response

2024-04-30 19:45:24,205 
INFO 
call was a success for 0: +
        male docs: 5, female docs: 7 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\active_call_methods.py", line 115, in handle_successful_call

2024-04-30 19:45:35,521 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:45:35,757 
INFO 
Round of calls done 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 102, in call_all_clinics

2024-04-30 19:51:57,414 
INFO 
Received phone number: 2894007562. Received clinic id: 60 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:51:57,415 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:51:57,895 
INFO 
Call started...sid: CA4892c9fda2d4664efbeb88276040f4a3 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 75, in call_all_clinics

2024-04-30 19:52:12,681 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:52:12,697 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:52:12,713 
INFO 
intro message timeouts count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:52:34,339 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:52:34,356 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:52:34,371 
INFO 
intro message timeouts count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:53:04,246 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:53:04,250 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 30, in <module>

2024-04-30 19:53:42,015 
INFO 
Received phone number: 2894007562. Received clinic id: 60 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_single_clinic.py", line 19, in make_call

2024-04-30 19:53:42,017 
INFO 
Starting flask server... 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\app.py", line 14, in start_server

2024-04-30 19:53:42,430 
INFO 
Call started...sid: CAf3f9e7b0120906884f8f7ce17fe34527 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 75, in call_all_clinics

2024-04-30 19:53:48,826 
INFO 
intro message retrys count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 23, in intro_message

2024-04-30 19:53:48,842 
INFO 
intro message invalid key count: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 24, in intro_message

2024-04-30 19:53:48,857 
INFO 
intro message timeouts count: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 25, in intro_message

2024-04-30 19:53:56,273 
INFO 
invalid key count on intro message: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 69, in handle_intro_message_response

2024-04-30 19:53:56,288 
INFO 
prompt retrys count on intro message: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 70, in handle_intro_message_response

2024-04-30 19:53:56,403 
INFO 
timeouts_count when asking male doctors number: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 111, in ask_male_doctors_number

2024-04-30 19:54:05,726 
INFO 
invalid_input_count when asking male doctors number: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 148, in handle_number_male_doctors_response

2024-04-30 19:54:05,742 
INFO 
male doctors: 3 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 161, in handle_number_male_doctors_response

2024-04-30 19:54:05,869 
INFO 
timeouts_count when asking for female doctors number: 0 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 197, in ask_female_doctors_number

2024-04-30 19:54:13,226 
INFO 
invalid_input_count when asking female doctors number: 1 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 237, in handle_number_female_doctors_response

2024-04-30 19:54:13,241 
INFO 
female doctors: 4 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\controller\call_flow_manager.py", line 248, in handle_number_female_doctors_response

2024-04-30 19:54:13,658 
INFO 
call was a success for 60: +
        male docs: 3, female docs: 4 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\active_call_methods.py", line 115, in handle_successful_call

2024-04-30 19:54:23,174 
INFO 
final call status is: 'completed' 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 47, in check_call_status

2024-04-30 19:54:23,400 
INFO 
Round of calls done 
 	from File "C:\Users\Sabih\Documents\coding\find-a-doc\src\services\calls\call_all_clinics.py", line 103, in call_all_clinics

